### ISSUE TITLE
input file gets created even when input is piped

### ISSUE THREAD

**Issue by Arnaudv6** [rcmdnk/sentaku#11]
Hello rcmdnk
This is rather an improvement request than a bug report:
I exclusively run sentaku by piping input to it, but it creates "~/.sentaku_input" empty file all the same.
I would expect it does not, if possible at all.

By the way there is a typo in both "README.md" and "sentaku -h": iput -> input
Thanks again for this soft.

**Comment by rcmdnk** [comment]
Thanks for the feedback.
 Actually it is unintended, so I fixed not to make input file for stdin input.
(and fixed typo, thanks!)

**Comment by Arnaudv6** [comment]
Working great, thanks.
