### ISSUE TITLE
Freeze with thousands of values since v4.5

### ISSUE THREAD

**Issue by Arnaudv6** [rcmdnk/sentaku#5]
Hello rcmdnk,
I use sentaku to display a huge list...
but since version 4.5 I can not any more : sentaku gets stuck.
Can you please get it to work again ?
Thanks for the awesome work !

**Comment by rcmdnk** [comment]
Thank you for the feedback.

Which shell are you using? (Zsh/Bash version?)
Could you please give me an error message you got, if any?

If possible, could you please try to use v4.4 or earlier and
find from which version the problem started?

**Comment by Arnaudv6** [comment]
```
bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
```
Yes :smile: I tried 4.4 and it is OK
No error message, sorry

here is my command `find ~/Music/ | sed 's/\x27/\\\x27/g' | sort | sentaku -N -s $'\n'`
when I lessen the number of files, it gets better :
300 values are OK
1600 values take ~4seconds to generate in v4.5, when it was a breeze in v4.4
18000 takes forever : I did not wait for it.

Hope this helps, thanks again.

**Comment by rcmdnk** [comment]
Thanks!
yes, I got the same result.

The main change is for the older shell:

Use:

    for i in $(seq 0 999);do

insted of

    for((i=0; i<1000;i++));do

which (`((~))`) is not available in the older shell.

I didn't think this affects on the performance,
but if it affects like this, i think I should choose the performance.

Let me check a little more.

**Comment by rcmdnk** [comment]
ok, the problem is not a `for`, but 1s array initialization:

> [for adding to array, use x[$i]=X, instead of x=(${x[@]} X), to make i… · rcmdnk/sentaku@710582f](https://github.com/rcmdnk/sentaku/commit/710582fe2b849d1cf6a72d2ece20c1cf4b3a61d9)

I switched it back in v0.4.6.

**Comment by Arnaudv6** [comment]
Yes : version 0.46 works like a charm !
thank you much for your awesome work, rcmdnk !
For the record, here is my chief use of sentaku:
http://www.arnaudv6.com/m
Thanks ! closing
