### ISSUE TITLE
File content preview

### ISSUE THREAD

**Issue by edoz90** [rcmdnk/sentaku#9]
Hi! :)
Great work.

What do you think about making a view of the content of the file or a preview right or after the selection list?
It will be difficult to implement?

**Comment by rcmdnk** [comment]
It could be like:

https://gist.github.com/rcmdnk/d7a29b8c9e16fd4cada19cc74832f94b

Usage is same as `sentaku`, like:

    $ ls |  /PATH/TO/file_selector

(if `file_sleector` is under `$PATH`, `/PATH/TO/` is not needed.)

This wrapper script shows the file content below, and shows more content when you push `s`.

or simpler implementation only `s` function (much faster):

https://gist.github.com/rcmdnk/ba0b97f94b290ced8bc8ca6657981b9a

**Comment by edoz90** [comment]
Yeah! The first one is great, thanks! :D

Is it possibile to achieve something like ranger? Maybe choosing where to show the preview...

![ranger](https://cloud.githubusercontent.com/assets/6991986/20867090/a95003f6-ba3c-11e6-8d2c-1260041edac0.png)

**Comment by rcmdnk** [comment]
file_selector has been added in the repository:

https://github.com/rcmdnk/sentaku/blob/master/bin/file_selector

Now, you can use "--right" or "--under" option, showing a content in the right or under the list, respectively.
Default is "right".
Can be changed by _SENTAKU_CONTENT_SHOW_UNDER variable, like

    $ ls |_SENTAKU_CONTENT_SHOW_UNDER=1 ./file_selector

This is same as `./file_selector --under`.
Or set 

    $ export  _SENTAKU_CONTENT_SHOW_UNDER=1

How about it?

**Comment by edoz90** [comment]
OMG! 😃 
You're great!!

![screenshot from 2016-12-04 19-32-24](https://cloud.githubusercontent.com/assets/6991986/20868290/71b6e042-ba58-11e6-950f-679059fb193c.png)

Thank you so much 🍺

**Comment by rcmdnk** [comment]
I have updated the script in the different repository: [shell-explorer](https://github.com/rcmdnk/shell-explorer)
